// <auto-generated />
using System;
using CutoverManager.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CutoverManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CutoverManager.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailResponsavel")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeResponsavel")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdExecutor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMarco")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPlano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSistema")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RiscoGoLive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Termino")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdExecutor");

                    b.HasIndex("IdMarco");

                    b.HasIndex("IdPlano");

                    b.HasIndex("IdSistema");

                    b.ToTable("Atividade", (string)null);
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Executor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdArea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("Executor", (string)null);
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Marco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marco", (string)null);
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Termino")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plano", (string)null);
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdArea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("Sistema", (string)null);
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Atividade", b =>
                {
                    b.HasOne("CutoverManager.Domain.Entities.Executor", "Executor")
                        .WithMany("Atividades")
                        .HasForeignKey("IdExecutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CutoverManager.Domain.Entities.Marco", "Marco")
                        .WithMany("Atividades")
                        .HasForeignKey("IdMarco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CutoverManager.Domain.Entities.Plano", "Plano")
                        .WithMany("Atividades")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CutoverManager.Domain.Entities.Sistema", "Sistema")
                        .WithMany("Atividades")
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Executor");

                    b.Navigation("Marco");

                    b.Navigation("Plano");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Executor", b =>
                {
                    b.HasOne("CutoverManager.Domain.Entities.Area", "Area")
                        .WithMany("Executores")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Sistema", b =>
                {
                    b.HasOne("CutoverManager.Domain.Entities.Area", "Area")
                        .WithMany("Sistemas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Area", b =>
                {
                    b.Navigation("Executores");

                    b.Navigation("Sistemas");
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Executor", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Marco", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Plano", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("CutoverManager.Domain.Entities.Sistema", b =>
                {
                    b.Navigation("Atividades");
                });
#pragma warning restore 612, 618
        }
    }
}
