// <auto-generated />
using System;
using CutoverPlanner.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CutoverPlanner.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailResponsavel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdExecutor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMarco")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSistema")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkRepositorio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredecessorasRaw")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RiscoGoLive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Termino")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdExecutor");

                    b.HasIndex("IdMarco");

                    b.HasIndex("IdSistema");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Executor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdArea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("Executores");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Marco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marcos");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdArea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("Sistemas");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Atividade", b =>
                {
                    b.HasOne("CutoverPlanner.Domain.Models.Executor", "Executor")
                        .WithMany("Atividades")
                        .HasForeignKey("IdExecutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CutoverPlanner.Domain.Models.Marco", "Marco")
                        .WithMany("Atividades")
                        .HasForeignKey("IdMarco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CutoverPlanner.Domain.Models.Sistema", "Sistema")
                        .WithMany("Atividades")
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Executor");

                    b.Navigation("Marco");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Executor", b =>
                {
                    b.HasOne("CutoverPlanner.Domain.Models.Area", "Area")
                        .WithMany("Executores")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Sistema", b =>
                {
                    b.HasOne("CutoverPlanner.Domain.Models.Area", "Area")
                        .WithMany("Sistemas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Area", b =>
                {
                    b.Navigation("Executores");

                    b.Navigation("Sistemas");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Executor", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Marco", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("CutoverPlanner.Domain.Models.Sistema", b =>
                {
                    b.Navigation("Atividades");
                });
#pragma warning restore 612, 618
        }
    }
}
