// <auto-generated />
using System;
using CutoverPlanner.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CutoverPlanner.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CutoverPlanner.Web.Models.AreaExecutora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Executor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gerencia")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAreaExecutora")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Torre")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AreasExecutoras");
                });

            modelBuilder.Entity("CutoverPlanner.Web.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaExecutoraNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriterioAceite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidencias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Executor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdPlanilha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkRepositorio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metricas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Milestone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredecessorasRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("Procedimento")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequerTestePerformance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsavel")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RiscoGoLive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sistema")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTeste")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("CutoverPlanner.Web.Models.AtividadeDependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtividadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PredecessoraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("PredecessoraId");

                    b.ToTable("AtividadeDependencias");
                });

            modelBuilder.Entity("CutoverPlanner.Web.Models.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barramento")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Integracao")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sistemas")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoIntegracao")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("CutoverPlanner.Web.Models.AtividadeDependencia", b =>
                {
                    b.HasOne("CutoverPlanner.Web.Models.Atividade", "Atividade")
                        .WithMany("Predecessoras")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CutoverPlanner.Web.Models.Atividade", "Predecessora")
                        .WithMany("Sucessoras")
                        .HasForeignKey("PredecessoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("Predecessora");
                });

            modelBuilder.Entity("CutoverPlanner.Web.Models.Atividade", b =>
                {
                    b.Navigation("Predecessoras");

                    b.Navigation("Sucessoras");
                });
#pragma warning restore 612, 618
        }
    }
}
